on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: fail
      run: 'false'

  second:
    needs:
    - first
    runs-on: ubuntu-latest
    steps:
    - name: pass?
      run: 'echo I guess?'

  failure:
    runs-on: ubuntu-latest
    needs:
      - first
      - second
    steps:
    - uses: garnercorp/build-actions/failure@add-action-to-handle-failed-dependencies
