on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: fail
      run: 'false'

  second:
    runs-on: ubuntu-latest
    steps:
    - name: fail
      run: 'true'

  failure:
    runs-on: ubuntu-latest
    needs:
      - first
      - second
    if: (success() || failure())
    steps:
    - uses: garnercorp/build-actions/failure@add-action-to-handle-failed-dependencies
      with:
        needs-json: ${{ toJSON(needs) }}
